### PR TITLE
Utf8 fixing, "active" patch

### PR DESCRIPTION
**Pull request by Kopilov**
Support C.UTF-8 (at least, in GNU/Linux)

### CODE REVIEW

**Comment by jbytecode** [comment]
@Kopilov the manuscript is in review, it is risky to stay in an inconsistent state, is this pr problematic in Macos? Have you got mvn test it?

**Comment by Kopilov** [comment]
Yes, but only in Linux (including GitHub Actions in PR where we can try to remove switching to en_US.UTF-8). I do not have any device with MacOS, sorry.

**Comment by jbytecode** [comment]
Can we add macos builds in actions?
It is important to be product ready in all platforms because we are in review process in the journal.

**Comment by Kopilov** [comment]
[jobs.run-on](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on) give this possibility. But building on MacOS is absolutely new for me, I can not promise any terms

**Comment by jbytecode** [comment]
I tried mvn test in macos, UTF test still fails.
I think it is the best option to disable it until it solves, because one of the reviewers may use Macos and they may havent enough time to fix it and making ready for testing.

**Comment by Kopilov** [comment]
@jbytecode what is standard command in MacOS to install R?

**Comment by Kopilov** [comment]
> I think it is the best option to disable it until it solves

OK

**Pull request merged**
